matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${MATRIX_EVAL}"

language: cpp

script:
        - chmod +x ./CI-script/build_run_test.CI.sh && bash ./CI-script/build_run_test.CI.sh
